# head
menu:
  カタログ/（目录）: /archives
  # sitemap: /sitemap.xml
  # other menus

links: 
  Github: https://github.com/x-bao
  Diary: https://meng.bi
  Blog: /archives
  Resume: https://meng.bi


rss: /atom.xml
favicon: /img/favicon.ico

date_format: 'MMMM D, YYYY'

google_verification: '9uRq2WvEIEs14TFqYBsFj9bQac1_CUiUxlgWvWnNtTo'  # your token
google_analytics: 'UA-80885450-4'   # your id

livere_id: 'city'
livere_uid: 'MTAyMC8zMzg4OC8xMDQ0MQ=='

start_year: 2017

# 备案信息
site_record: '（鄂ICP备17002258号-2）'

reward_images: # add your qr image
# - type: '微信'
  # url: '/img/wechat.png'
# - type: '支付宝' 
  # url: '/img/wechat.png'
 
