# head
menu:
  カタログ/（目录）: /archives
  # sitemap: /sitemap.xml
  # other menus

links: 
  Blog: /archives
  Diary: https://sanbf.cn
  Slaughter: https://sanbf.cn
  Github: https://github.com/x-bao
  About: https://sanbf.cn

rss: /atom.xml
favicon: /img/favicon.ico

date_format: 'MM-DD, YYYY'

google_verification: 'yVLudwcqIQlJbqhCeKLJZ8W_I1OJeVE8p30fz1mRhLM'  # your token
google_analytics: 'UA-80885450-5'   # your id

livere_id: 'city'
livere_uid: 'MTAyMC8zMzg4OC8xMDQ0MQ=='

start_year: 2017

# custom config
show_back_to_top: true
show_jump_to_next: true

# 备案信息
site_record: '（鄂ICP备17002258号-2）'

reward_images: # add your qr image
# - type: '微信'
  # url: '/img/wechat.png'
# - type: '支付宝' 
  # url: '/img/wechat.png'
